### ISSUE TITLE
cached_network_image-0.4.2/lib/cached_network_image.dart:464:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.

### ISSUE THREAD

**Issue by SGZoom** [dongjunkun/flutter_gank#1]
cached_network_image-0.4.2/lib/cached_network_image.dart:464:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.

**Comment by SGZoom** [comment]
Fix the problem by use:cached_network_image: ^0.8.0

**Comment by MaoHui2016** [comment]
Another exception was thrown: Controller's length property (9) does not match the

**Comment by dongjunkun** [comment]
已修复
